#pragma once
/*
enum p1_states
{
	ST_UNKNOWN,

	ST_IDLE,
	ST_WALK_FORWARD,
	ST_WALK_BACKWARD,
	ST_JUMP_NEUTRAL,
	ST_JUMP_FORWARD,
	ST_JUMP_BACKWARD,
	ST_CROUCH,
	ST_PUNCH_STANDING_L,
	ST_PUNCH_NEUTRAL_JUMP,
	ST_PUNCH_FORWARD_JUMP,
	ST_PUNCH_BACKWARD_JUMP,
	ST_PUNCH_CROUCH,
	ST_HIT
};

enum p1_inputs
{
	IN_LEFT_DOWN,
	IN_LEFT_UP,
	IN_RIGHT_DOWN,
	IN_RIGHT_UP,
	IN_LEFT_AND_RIGHT,
	IN_JUMP,
	IN_CROUCH_UP,
	IN_CROUCH_DOWN,
	IN_JUMP_AND_CROUCH,
	IN_X, // X = PUNCH
	IN_H, // J = HIT
	IN_JUMP_FINISH,
	IN_PUNCH_FINISH,
	IN_HIT_FINISH
};*/

/**
*States
**/

enum p1_states
{
	//Player 1
	_1_ST_UNKNOWN,

	_1_ST_IDLE,
	_1_ST_WALK_FORWARD,
	_1_ST_WALK_BACKWARD,
	_1_ST_JUMP_NEUTRAL,
	_1_ST_JUMP_FORWARD,
	_1_ST_JUMP_BACKWARD,
	_1_ST_CROUCH,
	_1_ST_PUNCH_STANDING_L,
	//_1_ST_PUNCH_STANDING_M,
	_1_ST_PUNCH_STANDING_H,
	_1_ST_KICK_STANDING_L,
	//_1_ST_KICK_STANDING_M,
	_1_ST_KICK_STANDING_H,
	_1_ST_PUNCH_NEUTRAL_JUMP,
	_1_ST_PUNCH_FORWARD_JUMP,
	_1_ST_PUNCH_BACKWARD_JUMP,
	_1_ST_PUNCH_CROUCH,
	_1_ST_HIT,
	_1_ST_STUN,
};
enum p2_states{
	//Player 2
	_2_ST_UNKNOWN,

	_2_ST_IDLE,
	_2_ST_WALK_FORWARD,
	_2_ST_WALK_BACKWARD,
	_2_ST_JUMP_NEUTRAL,
	_2_ST_JUMP_FORWARD,
	_2_ST_JUMP_BACKWARD,
	_2_ST_CROUCH,
	_2_ST_PUNCH_STANDING_L,
	//_2_ST_PUNCH_STANDING_M,
	_2_ST_PUNCH_STANDING_H,
	_2_ST_KICK_STANDING_L,
	//_2_ST_KICK_STANDING_M,
	_2_ST_KICK_STANDING_H,
	_2_ST_PUNCH_NEUTRAL_JUMP,
	_2_ST_PUNCH_FORWARD_JUMP,
	_2_ST_PUNCH_BACKWARD_JUMP,
	_2_ST_PUNCH_CROUCH,
	_2_ST_HIT,
	_2_ST_STUN
};
/**
*Inputs
**/
enum p1_inputs
{
	//Player 1
	_1_IN_LEFT_DOWN,
	_1_IN_LEFT_UP,
	_1_IN_RIGHT_DOWN,
	_1_IN_RIGHT_UP,
	_1_IN_LEFT_AND_RIGHT,
	_1_IN_JUMP,
	_1_IN_CROUCH_UP,
	_1_IN_CROUCH_DOWN,
	_1_IN_JUMP_AND_CROUCH,
	_1_IN_L_PUNCH,	
	_1_IN_H_PUNCH,	
	_1_IN_L_KICK,	
	_1_IN_H_KICK,	
	_1_IN_HIT,		
	_1_IN_JUMP_FINISH,
	_1_IN_PUNCH_FINISH,
	_1_IN_HIT_FINISH,
};

enum p2_inputs
{
	//Player 2
	_2_IN_LEFT_DOWN,
	_2_IN_LEFT_UP,
	_2_IN_RIGHT_DOWN,
	_2_IN_RIGHT_UP,
	_2_IN_LEFT_AND_RIGHT,
	_2_IN_JUMP,
	_2_IN_CROUCH_UP,
	_2_IN_CROUCH_DOWN,
	_2_IN_JUMP_AND_CROUCH,
	_2_IN_L_PUNCH,
	_2_IN_H_PUNCH,
	_2_IN_L_KICK, 
	_2_IN_H_KICK, 
	_2_IN_HIT, 
	_2_IN_JUMP_FINISH,
	_2_IN_PUNCH_FINISH,
	_2_IN_HIT_FINISH
};

